-- Active: 1731502597388@@127.0.0.1@3306@test
CREATE TABLE `employees`(
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `first_name` VARCHAR(50) NOT NULL,
    `email` VARCHAR(50) NOT NULL,
    `salary` BIGINT(20) UNSIGNED,
    `designation` VARCHAR(50) NOT NULL
)

INSERT INTO `employees` (`first_name`, `email`, `salary`, `designation`) VALUES
('John', 'john@example.com', 70000, 'Software Engineer'),
('Emily', 'emily@example.com', 85000, 'Product Manager'),
('Michael', 'michael@example.com', 60000, 'Data Analyst'),
('Sarah', 'sarah@example.com', 75000, 'Project Coordinator'),
('David', 'david@example.com', 95000, 'Software Architect'),
('Emma', 'emma@example.com', 65000, 'Web Developer'),
('James', 'james@example.com', 50000, 'Technical Support'),
('Olivia', 'olivia@example.com', 72000, 'Marketing Specialist'),
('Daniel', 'daniel@example.com', 68000, 'UX Designer'),
('Sophia', 'sophia@example.com', 90000, 'Product Designer'),
('Liam', 'liam@example.com', 78000, 'Business Analyst'),
('Mia', 'mia@example.com', 85000, 'Software Engineer'),
('Noah', 'noah@example.com', 70000, 'Quality Assurance'),
('Ava', 'ava@example.com', 64000, 'HR Specialist'),
('William', 'william@example.com', 93000, 'Backend Developer'),
('Isabella', 'isabella@example.com', 76000, 'Data Scientist'),
('Ethan', 'ethan@example.com', 80000, 'Frontend Developer'),
('Charlotte', 'charlotte@example.com', 67000, 'Content Writer'),
('Mason', 'mason@example.com', 71000, 'DevOps Engineer'),
('Amelia', 'amelia@example.com', 87000, 'Systems Analyst'),
('Logan', 'logan@example.com', 94000, 'Full Stack Developer'),
('Harper', 'harper@example.com', 58000, 'Graphic Designer'),
('Lucas', 'lucas@example.com', 81000, 'SEO Specialist'),
('Evelyn', 'evelyn@example.com', 74000, 'Data Engineer'),
('Alexander', 'alexander@example.com', 88000, 'Mobile Developer'),
('Ella', 'ella@example.com', 56000, 'Office Manager'),
('Aiden', 'aiden@example.com', 82000, 'IT Consultant'),
('Grace', 'grace@example.com', 61000, 'Operations Coordinator'),
('Samuel', 'samuel@example.com', 96000, 'Lead Developer'),
('Victoria', 'victoria@example.com', 70000, 'Sales Executive'),
('Sebastian', 'sebastian@example.com', 69000, 'Finance Manager'),
('Lily', 'lily@example.com', 62000, 'Recruiter'),
('Jack', 'jack@example.com', 90000, 'Solutions Architect'),
('Aria', 'aria@example.com', 79000, 'Copywriter'),
('Henry', 'henry@example.com', 87000, 'Compliance Officer'),
('Chloe', 'chloe@example.com', 66000, 'Data Analyst'),
('Andrew', 'andrew@example.com', 89000, 'Security Engineer'),
('Lillian', 'lillian@example.com', 60000, 'Product Support'),
('Joshua', 'joshua@example.com', 71000, 'Network Engineer'),
('Sofia', 'sofia@example.com', 84000, 'Project Manager'),
('Christopher', 'christopher@example.com', 93000, 'AI Engineer'),
('Zoe', 'zoe@example.com', 77000, 'Social Media Manager'),
('Matthew', 'matthew@example.com', 67000, 'Research Analyst'),
('Avery', 'avery@example.com', 72000, 'Business Development'),
('Dylan', 'dylan@example.com', 75000, 'System Administrator'),
('Riley', 'riley@example.com', 81000, 'Digital Strategist'),
('Nathan', 'nathan@example.com', 83000, 'Software Tester'),
('Hannah', 'hannah@example.com', 59000, 'Administrative Assistant'),
('Ryan', 'ryan@example.com', 85000, 'Cloud Architect'),
('Leah', 'leah@example.com', 65000, 'Event Coordinator'),
('Carter', 'carter@example.com', 78000, 'Database Administrator'),
('Nora', 'nora@example.com', 70000, 'Customer Support'),
('Isaac', 'isaac@example.com', 94000, 'Blockchain Developer'),
('Scarlett', 'scarlett@example.com', 76000, 'Content Strategist'),
('Owen', 'owen@example.com', 89000, 'Site Reliability Engineer'),
('Stella', 'stella@example.com', 63000, 'Communications Specialist'),
('Caleb', 'caleb@example.com', 81000, 'Risk Manager'),
('Addison', 'addison@example.com', 70000, 'Office Clerk'),
('Christian', 'christian@example.com', 68000, 'Technical Writer'),
('Paisley', 'paisley@example.com', 85000, 'UI/UX Researcher'),
('Jonathan', 'jonathan@example.com', 88000, 'App Developer'),
('Audrey', 'audrey@example.com', 74000, 'Talent Acquisition'),
('Aaron', 'aaron@example.com', 92000, 'Machine Learning Engineer'),
('Hazel', 'hazel@example.com', 67000, 'Brand Strategist'),
('Charles', 'charles@example.com', 87000, 'Scrum Master'),
('Aurora', 'aurora@example.com', 64000, 'HR Assistant'),
('Thomas', 'thomas@example.com', 94000, 'Big Data Engineer'),
('Savannah', 'savannah@example.com', 72000, 'Supply Chain Manager'),
('Hunter', 'hunter@example.com', 80000, 'Penetration Tester'),
('Bella', 'bella@example.com', 62000, 'Marketing Analyst'),
('Adrian', 'adrian@example.com', 91000, 'Embedded Systems Engineer'),
('Natalie', 'natalie@example.com', 78000, 'Sales Operations'),
('Jeremiah', 'jeremiah@example.com', 88000, 'Software Trainer'),
('Violet', 'violet@example.com', 57000, 'HR Generalist'),
('Eli', 'eli@example.com', 93000, 'Ethical Hacker'),
('Claire', 'claire@example.com', 69000, 'Legal Advisor'),
('Connor', 'connor@example.com', 81000, 'Technical Recruiter'),
('Penelope', 'penelope@example.com', 86000, 'Customer Success Manager'),
('Isaiah', 'isaiah@example.com', 75000, 'IT Specialist'),
('Lucy', 'lucy@example.com', 66000, 'Content Editor'),
('Nolan', 'nolan@example.com', 94000, 'Solutions Consultant'),
('Brooklyn', 'brooklyn@example.com', 70000, 'Product Marketer'),
('Adam', 'adam@example.com', 72000, 'Financial Analyst'),
('Ellie', 'ellie@example.com', 67000, 'Assistant Manager'),
('Julian', 'julian@example.com', 85000, 'DevOps Specialist'),
('Sadie', 'sadie@example.com', 78000, 'Brand Manager'),
('Landon', 'landon@example.com', 87000, 'Product Owner'),
('Peyton', 'peyton@example.com', 61000, 'Account Coordinator'),
('Lucas', 'lucas.j@example.com', 88000, 'SEO Analyst'),
('Bailey', 'bailey@example.com', 53000, 'Office Assistant'),
('Cameron', 'cameron@example.com', 83000, 'Quality Manager'),
('Hailey', 'hailey@example.com', 75000, 'Social Media Coordinator'),
('Brayden', 'brayden@example.com', 69000, 'Junior Developer'),
('Maya', 'maya@example.com', 84000, 'Public Relations'),
('Easton', 'easton@example.com', 81000, 'API Developer'),
('Skylar', 'skylar@example.com', 66000, 'UX Researcher'),
('Jaxon', 'jaxon@example.com', 89000, 'Data Engineer'),
('Paisley', 'paisley.m@example.com', 72000, 'Content Marketer'),
('Colton', 'colton@example.com', 78000, 'Technical Consultant'),
('Paisley', 'paisley.s@example.com', 59000, 'Receptionist'),
('Jasper', 'jasper@example.com', 75000, 'Data Scientist'),
('Gabriella', 'gabriella@example.com', 86000, 'HR Consultant');
